[package]
name = "simple_gpui_core"
version = "0.2.0"
edition = "2024"
description = "Core library for simple-gpui, providing procedural macros and utilities for building GUI components."
license = "MIT"
documentation = "https://docs.rs/simple_gpui_core"
homepage = "https://github.com/zrll12/simple-gpui"
repository = "https://github.com/zrll12/simple-gpui"

[dependencies]
quote = "1.0.44"
syn = { version = "2.0.117", features = ["full"] }
case = "1.0.0"
proc-macro2 = "1.0.106"

[lib]
proc-macro = true

[dev-dependencies]
trybuild = "1.0"