[package]
name = "simple-gpui"
version = "0.3.0"
edition = "2024"
description = "A simple declarative API for gpui."
license = "MIT"
documentation = "https://docs.rs/simple-gpui"
homepage = "https://github.com/zrll12/simple-gpui"
repository = "https://github.com/zrll12/simple-gpui"

[dependencies]
simple_gpui_core = { version="0.3.0", path = "./simple_gpui_core" }

[dev-dependencies]
# These dependencies are only used for examples.
gpui = "0.2.2"
gpui-component = "0.5.1"
rfd = "0.17.2"